const ERROR_CODES = {
  MISSING_FIELDS: 'MISSING_FIELDS',
  SERVER_ERROR: 'SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  USER_EXISTS: 'USER_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TEAM_EXISTS: 'TEAM_EXISTS',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  ALREADY_PLAYED: 'ALREADY_PLAYED',
  INVALID_SCORE: 'INVALID_SCORE'
};

const TOURNAMENT_STATES = {
  DRAFT: 'draft',
  INSCRIPCION: 'inscripcion',
  EN_CURSO: 'en_curso',
  FINALIZADO: 'finalizado'
};

const TOURNAMENT_CATEGORY_STATES = {
  INSCRIPCION_ABIERTA: 'inscripcion_abierta',
  INSCRIPCION_CERRADA: 'inscripcion_cerrada',
  ZONAS_GENERADAS: 'zonas_generadas',
  ZONAS_EN_CURSO: 'zonas_en_curso',
  PLAYOFFS_GENERADOS: 'playoffs_generados',
  FINALIZADO: 'finalizado'
};

const REGISTRATION_STATES = {
  INSCRIPTO: 'inscripto',
  CONFIRMADO: 'confirmado',
  CANCELADO: 'cancelado'
};

const TEAM_STATES = {
  ACTIVA: 'activa',
  INACTIVA: 'inactiva'
};

const MATCH_STATES = {
  PENDING: 'pending',
  SCHEDULED: 'scheduled',
  PLAYED: 'played',
  BYE: 'bye'
};

const MATCH_FORMATS = {
  BEST_OF_3_SUPER_TB: 'BEST_OF_3_SUPER_TB',
  BEST_OF_3_FULL: 'BEST_OF_3_FULL'
};

const SET_TYPES = {
  NORMAL: 'NORMAL',
  SUPER_TB: 'SUPER_TB'
};

const USER_ROLES = {
  ADMIN: 'admin',
  PLAYER: 'player'
};

const CATEGORY_GENDERS = {
  CABALLEROS: 'caballeros',
  DAMAS: 'damas'
};

const PLAYER_GENDERS = {
  M: 'M',
  F: 'F'
};

const DEFAULT_VALUES = {
  MATCH_FORMAT: 'BEST_OF_3_SUPER_TB',
  SUPER_TIEBREAK_POINTS: 10,
  WIN_POINTS: 2,
  LOSS_POINTS: 0,
  TIEBREAK_IN_SETS: true
};

module.exports = {
  ERROR_CODES,
  TOURNAMENT_STATES,
  TOURNAMENT_CATEGORY_STATES,
  REGISTRATION_STATES,
  TEAM_STATES,
  MATCH_STATES,
  MATCH_FORMATS,
  SET_TYPES,
  USER_ROLES,
  CATEGORY_GENDERS,
  PLAYER_GENDERS,
  DEFAULT_VALUES
};
